[package]
authors = ["David Weis <davidmichaelweis@gmail.com>"]
description = "Remote controller and telemetry display for robots for the Steam Deck"
edition = "2021"
license = "MIT OR APACHE"
name = "deck-robot-remote"
publish = false
readme = "README.md"
repository = "https://github.com/dmweis/deck-robot-remote"
version = "0.1.0"


[dependencies]
anyhow = { version = "1.0.95", features = ["backtrace"] }
chrono = { version = "0.4.39", features = ["serde"] }
clap = { version = "4.5.29", features = ["derive"] }
thiserror = "2.0.11"
tokio = { version = "1.43.0", features = ["full"] }

# logging
tracing = { version = "0.1.41", features = ["log"] }
tracing-subscriber = { version = "0.3.19", features = [
  "registry",
  "env-filter",
  "json",
] }

# serialization
schemars = { version = "0.8.21", features = ["chrono"] }
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.138"
serde_yaml = "0.9.34"


open = "5.3.2"

# Windows xinput
[target.'cfg(windows)'.dependencies]
gilrs = { version = "0.11.0", features = [
  "serde-serialize",
  "xinput",
], default-features = false }

# Linux wgi
[target.'cfg(not(windows))'.dependencies]
gilrs = { version = "0.11.0", features = [
  "serde-serialize",
  "wgi",
], default-features = false }
