protobuf_subscriptions:
  - topic: "rplidar/point_cloud"
    proto_type: "foxglove.PointCloud"
  - topic: "rplidar/laser_scan"
    proto_type: "foxglove.LaserScan"

json_subscriptions:
  - topic: "hopper_wakeword/event/wake_word_detection"
    type_name: "WakeWordDetection"
    json_schema_name: "GENERIC_JSON_SCHEMA"
